twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        appService: '@App\Services\AppService'
        languagesService: '@App\Services\Languages'
        cartService: '@App\Services\CartService'
